#!/bin/sh

if [ -z "$1" ] ; then
	echo "usage: $0 <logfile> [process_name_pattern]"
	exit 1
elif [ -z "$2" ] ; then
	echo "Logging all output to $1"
	rm $1
	while true; do
		pidstat -drsuh >> $1
		sleep 1
	done
else
	echo "Logging all output for patter $2 to file $1"
	rm $1
	while true; do
		pidstat -drsuh -C $2 >> $1
		sleep 1
	done
fi
