#!/bin/sh

if [ -z "$1" ] ; then
	echo "usage: $0 <logfile> [process_name_pattern]"
	exit 1
fi

echo "Logging output to $1"
pidstat -drsuh -p ALL | sed '1d;/^$/d;s/#[ ]*Time/timestamp/g;s/^[ ]*//;s/[ ]\+/,/g' | head -n 1 > $1

if [ -z "$2" ] ; then
	exec pidstat -drush -p ALL 1 | sed '1d;/^[#]/d;/^$/d;s/^[ ]*//;s/[ ]\+/,/g' >> $1
else
	echo "... using pattern $2"
	exec pidstat -drush -p ALL -C $2 1 | sed '1d;/^[#]/d;/^$/d;s/^[ ]*//;s/[ ]\+/,/g' >> $1
fi
